/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * DTO de Usuario
 * @author apascual
 *
 */
public class UsuariosDto implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6498737100866914554L;


	//Constructor vacío
	public UsuariosDto() {
		super();
	}

	private Long idUsuario;
	private String codigoUsuario;
	private Long idProvincia;
	private String clave;
	private String nomApe;
	private String email;
	private String admin;
	private String observaciones;
	private Date fecCreacion;
	private Date fecBaja;


	// ----------------------------------------------------------------------
	// Getters & Setters
	// ----------------------------------------------------------------------
	public Long getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Long getIdProvincia() {
		return idProvincia;
	}

	public void setIdProvincia(Long idProvincia) {
		this.idProvincia = idProvincia;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getClave() {
		return this.clave;
	}

	public void setNomApe(String nomApe) {
		this.nomApe = nomApe;
	}

	public String getNomApe() {
		return this.nomApe;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return this.email;
	}

	public void setAdmin(String admin) {
		this.admin = admin;
	}

	public String getAdmin() {
		return this.admin;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecBaja(Date fecBaja) {
		this.fecBaja = fecBaja;
	}

	public Date getFecBaja() {
		return this.fecBaja;
	}

	public String getCodigoUsuario() {
		return codigoUsuario;
	}

	public void setCodigoUsuario(String codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	//**********************************************************************************
	//Métodos toString(), hashCode() y Equals()
	//**********************************************************************************
	
	@Override
	public String toString() {
		return "UsuariosEntity [idUsuario=" + idUsuario + ", codigoUsuario=" + codigoUsuario + ", idProvincia="
				+ idProvincia + ", clave=" + clave + ", nomApe=" + nomApe + ", email=" + email + ", admin=" + admin
				+ ", observaciones=" + observaciones + ", fecCreacion=" + fecCreacion + ", fecBaja=" + fecBaja + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idUsuario == null) ? 0 : idUsuario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UsuariosDto other = (UsuariosDto) obj;
		if (idUsuario == null) {
			if (other.idUsuario != null)
				return false;
		} else if (!idUsuario.equals(other.idUsuario))
			return false;
		return true;
	}


}
