/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "CAMPANA_ADHESION"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CAMPANA_ADHESION", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CampanaAdhesionEntity.countAll", query="SELECT COUNT(x) FROM CampanaAdhesionEntity x" )
} )
@SequenceGenerator(name= "campanaAdhesion_id_seq_gen", sequenceName="CINETI.SEQ_CAMPANA_ADHESION", allocationSize=5,initialValue=100)
public class CampanaAdhesionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "campanaAdhesion_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_ADHESION")
    private Long idAdhesion   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ID_CAMPANA")
    private Long idCampana   ;
    
    @Column(name="ID_ENTIDAD")
    private Long idEntidades   ;

    @Column(name="ID_ESTADO")
    private Long idEstadoAdhesion;   

	

	//----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_ENTIDAD", referencedColumnName="ID_ENTIDAD" , insertable=false, updatable=false)
    private EntidadesEntity entidades   ;
	
    @ManyToOne
    @JoinColumn(name="ID_ESTADO", referencedColumnName="ID_ESTADO", insertable=false, updatable=false)
    private EstadoAdhesionEntity estado;

    @ManyToOne
    @JoinColumn(name="ID_CAMPANA", referencedColumnName="ID_CAMPANA", insertable=false, updatable=false)
    private CampanaEntity campana     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CampanaAdhesionEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdCampana( Long idCampana ) {
        this.idCampana = idCampana ;
    }
    public Long getIdCampana() {
        return this.idCampana;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ID_ADHESION ( NUMBER ) 
    public void setIdAdhesion( Long idAdhesion ) {
        this.idAdhesion = idAdhesion;
    }
    public Long getIdAdhesion() {
        return this.idAdhesion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


	public Long getIdEntidades() {
		return idEntidades;
	}

	public void setIdEntidades(Long idEntidades) {
		this.idEntidades = idEntidades;
	}

	public Long getIdEstadoAdhesion() {
		return idEstadoAdhesion;
	}

	public void setIdEstadoAdhesion(Long idEstadoAdhesion) {
		this.idEstadoAdhesion = idEstadoAdhesion;
	}

	public EntidadesEntity getEntidades() {
		return entidades;
	}

	public void setEntidades(EntidadesEntity entidades) {
		this.entidades = entidades;
	}

	public EstadoAdhesionEntity getEstado() {
		return estado;
	}

	public void setEstado(EstadoAdhesionEntity estado) {
		this.estado = estado;
	}

	public CampanaEntity getCampana() {
		return campana;
	}

	public void setCampana(CampanaEntity campana) {
		this.campana = campana;
	}

	@Override
	public String toString() {
		return "CampanaAdhesionEntity [idAdhesion=" + idAdhesion + ", idCampana=" + idCampana + ", idEntidades="
				+ idEntidades + ", idEstadoAdhesion=" + idEstadoAdhesion + ", entidades=" + entidades + ", estado="
				+ estado + ", campana=" + campana + "]";
	} 

	
}
