/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "CAMPANA_PROVINCIA"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CAMPANA_PROVINCIA", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CampanaProvinciaEntity.countAll", query="SELECT COUNT(x) FROM CampanaProvinciaEntity x" )
} )
@SequenceGenerator(name= "campanaProvincia_id_seq_gen", sequenceName="CINETI.SEQ_CAMPANA_PROVINCIA", allocationSize=5,initialValue=100)
public class CampanaProvinciaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "campanaProvincia_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_CAMP_PROVINCIA")
    private Long idCampProvincia   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ID_CAMPANA")
    private Long idCampana   ;
    
    @Column(name="ID_PROVINCIA")
    private Long idProvincia   ;


	//----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_PROVINCIA", referencedColumnName="ID_PROVINCIA" , insertable=false, updatable=false)
    private ProvinciasEntity provincia   ;
	
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_CAMPANA", referencedColumnName="ID_CAMPANA", insertable=false, updatable=false)
    private CampanaEntity campana     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CampanaProvinciaEntity() {
		super();
    }
    
  
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ID_camp_provincia ( NUMBER ) 
   

	public Long getIdCampProvincia() {
		return idCampProvincia;
	}

	public void setIdCampProvincia(Long idCampProvincia) {
		this.idCampProvincia = idCampProvincia;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    public void setIdCampana( Long idCampana ) {
        this.idCampana = idCampana ;
    }
    public Long getIdCampana() {
        return this.idCampana;
    }

	public Long getIdProvincia() {
		return idProvincia;
	}

	public void setIdProvincia(Long idProvincia) {
		this.idProvincia = idProvincia;
	}

	public ProvinciasEntity getProvincia() {
		return provincia;
	}

	public void setProvincia(ProvinciasEntity provincia) {
		this.provincia = provincia;
	}

	public CampanaEntity getCampana() {
		return campana;
	}

	public void setCampana(CampanaEntity campana) {
		this.campana = campana;
	}


	@Override
	public String toString() {
		return "CampanaProvinciaEntity [idCampProvincia=" + idCampProvincia + ", idCampana=" + idCampana
				+ ", idProvincia=" + idProvincia + ", provincia=" + provincia + ", campana=" + campana + "]";
	}


	
}
