/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "CES_CONTACTOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CES_CONTACTOS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CesContactosEntity.countAll", query="SELECT COUNT(x) FROM CesContactosEntity x" )
} )
@SequenceGenerator(name= "cesContactos_id_seq_gen", sequenceName="CINETI.SEQ_CES_CONTACTOS", allocationSize=5,initialValue=100)
public class CesContactosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "cesContactos_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_CES_CONTACTOS", nullable=false)
    private Long idCesContactos    ;


	//----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@Column(name="ID_CESION")
    private Long idCesiones   ;
	

	@Column(name="ID_PERSONA")
    private Long idPersona   ;


	//----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


	@ManyToOne
    @JoinColumn(name="ID_CESION", referencedColumnName="ID_CESION", insertable=false, updatable=false)
    private CesionesEntity cesiones    ;
	


    @ManyToOne
    @JoinColumn(name="ID_PERSONA", referencedColumnName="ID_PERSONA", insertable=false, updatable=false)
    private PersContactoEntity persona;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CesContactosEntity() {
		super();
	}
    


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------


    public Long getIdCesContactos() {
		return idCesContactos;
	}



	public void setIdCesContactos(Long idCesContactos) {
		this.idCesContactos = idCesContactos;
	}



	public Long getIdCesiones() {
		return idCesiones;
	}



	public void setIdCesiones(Long idCesiones) {
		this.idCesiones = idCesiones;
	}


	public CesionesEntity getCesiones() {
		return cesiones;
	}



	public void setCesiones(CesionesEntity cesiones) {
		this.cesiones = cesiones;
	}

	public PersContactoEntity getPersona() {
		return persona;
	}



	public void setPersona(PersContactoEntity persona) {
		this.persona = persona;
	}

	public Long getIdPersona() {
		return idPersona;
	}

	public void setIdPersona(Long idPersona) {
		this.idPersona = idPersona;
	}

	@Override
	public String toString() {
		return "CesContactosEntity [idCesContactos=" + idCesContactos + ", idCesiones=" + idCesiones +
				", idPersona=" + idPersona + ", cesiones=" + cesiones + ", persona=" + persona + "]";
	}


    

}
