/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "CES_DOCUMENTOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CES_DOCUMENTOS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CesDocumentosEntity.countAll", query="SELECT COUNT(x) FROM CesDocumentosEntity x" ),
  @NamedQuery ( name="findCesDocumentosByIdCesion", query="SELECT d FROM CesDocumentosEntity d WHERE d.idCesion = :idCesion")
} )
@SequenceGenerator(name= "cesDoc_id_seq_gen", sequenceName="CINETI.SEQ_CES_DOCUMENTOS", allocationSize=5,initialValue=100)
public class CesDocumentosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "cesDoc_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_DOCUMENTO")
    private Long idDocumento;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="TIPO_DOC",length=100)
    private String tipoDocumento;

	@Column(name="NOMBRE", length=100)
    private String nombre;

	@Column(name="DESCRIPCION", length=250)
    private String descripcion;
	
    @Column(name="FEC_SUBIDA", nullable=false)
    private Date fecSubida;

    @Column(name="FORMATO", length=50)
    private String formato;

    @Column(name="ID_CESION", nullable=false)
	private Long idCesion;
    
    @Column(name="SIZE")
    private Long size;
    
    @Column(name="DATA")
    private byte[] data;
    
	public Long getIdDocumento() {
		return idDocumento;
	}

	public void setIdDocumento(Long idDocumento) {
		this.idDocumento = idDocumento;
	}

	public String getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFecSubida() {
		return fecSubida;
	}

	public void setFecSubida(Date fecSubida) {
		this.fecSubida = fecSubida;
	}

	public String getFormato() {
		return formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public Long getIdCesion() {
		return idCesion;
	}

	public void setIdCesion(Long idCesion) {
		this.idCesion = idCesion;
	}

	public Long getSize() {
		return size;
	}

	public void setSize(Long size) {
		this.size = size;
	}
	
	public byte[] getData() {
		return data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "CesDocumentosEntity [idDocumento=" + idDocumento + ", tipoDocumento=" + tipoDocumento + ", nombre="
				+ nombre + ", descripcion=" + descripcion + ", fecSubida=" + fecSubida + ", formato=" + formato
				+ ", idCesion=" + idCesion + ", size=" + size + "]";
	}
    
}