/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "CINEMOMETRO"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CINEMOMETRO", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CinemometroEntity.countAll", query="SELECT COUNT(x) FROM CinemometroEntity x" )
} )
@SequenceGenerator(name= "cinemometro_id_seq_gen", sequenceName="CINETI.SEQ_CINEMOMETRO", allocationSize=5,initialValue=100)
public class CinemometroEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    
    @Id
    @GeneratedValue(generator = "cinemometro_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_CINEMOMETRO", nullable=false)
    private Long     idCinemometro     ;

    @Column(name="ID_EQUIPAMIENTO")
    private Long idEquipamiento   ;


	@OneToOne(cascade=CascadeType.ALL)  
	@JoinColumn(name="ID_EQUIPAMIENTO", referencedColumnName="ID", insertable=false, updatable=false )
    private EquipamientoEntity     equipamiento     ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


	@Column(name="ANTENA", length=50)
    private String     antena       ;

    @Column(name="CAMARA", length=50)
    private String     camara       ;



    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CinemometroEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    
    public Long getIdEquipamiento() {
		return idEquipamiento;
	}

	public void setIdEquipamiento(Long idEquipamiento) {
		this.idEquipamiento = idEquipamiento;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    

    //--- DATABASE MAPPING : ANTENA ( VARCHAR2 ) 
    public void setAntena( String antena ) {
        this.antena = antena;
    }
    public String getAntena() {
        return this.antena;
    }

    //--- DATABASE MAPPING : CAMARA ( VARCHAR2 ) 
    public void setCamara( String camara ) {
        this.camara = camara;
    }
    public String getCamara() {
        return this.camara;
    }

  
	public Long getIdCinemometro() {
		return idCinemometro;
	}

	public void setIdCinemometro(Long idCinemometro) {
		this.idCinemometro = idCinemometro;
	}

	public EquipamientoEntity getEquipamiento() {
		return equipamiento;
	}

	public void setEquipamiento(EquipamientoEntity equipamiento) {
		this.equipamiento = equipamiento;
	}

	@Override
	public String toString() {
		return "CinemometroEntity [idCinemometro=" + idCinemometro + ", idEquipamiento=" + idEquipamiento
				+ ", equipamiento=" + equipamiento + ", antena=" + antena + ", camara=" + camara + "]";
	} 
	

}
