/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "CONVENIOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CONVENIOS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name = "ConveniosEntity.countAll", query="SELECT COUNT(x) FROM ConveniosEntity x" ),
  @NamedQuery( name = "findConveniosEntityByIdProvincia", query = "SELECT c FROM ConveniosEntity c WHERE c.entidades.localidades.idProvincia = :idProvincia ORDER BY c.fecIniConv DESC"),
  @NamedQuery( name = "findConveniosByIdLocalidad", query="SELECT c FROM ConveniosEntity c WHERE c.entidades.idLocalidades = :idLocalidades ORDER BY c.fecIniConv DESC"),
  @NamedQuery( name = "findConveniosByIdEntidad", query="SELECT c FROM ConveniosEntity c WHERE c.idEntidades = :idEntidades ORDER BY c.fecIniConv DESC")
} )
@SequenceGenerator(name= "convenios_id_seq_gen", sequenceName="CINETI.SEQ_CONVENIOS", allocationSize=5,initialValue=100)
public class ConveniosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "convenios_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_CONVENIO", nullable=false)
    private Long idConvenio   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ID_ENTIDAD")
    private Long idEntidades;

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_INI_CONV", nullable=false)
    private Date fecIniConv;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_FIRMA_CONV")
    private Date fecFirmaConv;

    @Column(name="OBSERVACIONES", length=300)
    private String observaciones;
    
    @Column(name="OBJETO_CONV", length=200)
    private String objetoConvenio;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_BAJA")
    private Date fecBaja;

    @Column(name="MOTIVO_BAJA", length=300)
    private String motivoBaja;

	// "idEntidad" (column "ID_ENTIDAD") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_ENTIDAD", referencedColumnName="ID_ENTIDAD", insertable=false, updatable=false)
    private EntidadesEntity entidades   ;
	
//    @ManyToMany(mappedBy="listOfConvenios", targetEntity=PersContactoEntity.class)
//    private List<PersContactoEntity> listOfPersContacto;
//

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ConveniosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdConvenio( Long idConvenio ) {
        this.idConvenio = idConvenio ;
    }
    public Long getIdConvenio() {
        return this.idConvenio;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FEC_INI_CONV ( DATE ) 
    
   
	
    public void setFecIniConv( Date fecIniConv ) {
        this.fecIniConv = fecIniConv;
    }
    public Date getFecIniConv() {
        return this.fecIniConv;
    }

    //--- DATABASE MAPPING : FEC_FIRMA_CONV ( DATE ) 
    public void setFecFirmaConv( Date fecFirmaConv ) {
        this.fecFirmaConv = fecFirmaConv;
    }
    public Date getFecFirmaConv() {
        return this.fecFirmaConv;
    }

    //--- DATABASE MAPPING : OBSERVACIONES ( VARCHAR2 ) 
    public void setObservaciones( String observaciones ) {
        this.observaciones = observaciones;
    }
    public String getObservaciones() {
        return this.observaciones;
    }

    //--- DATABASE MAPPING : FEC_BAJA ( DATE ) 
    public void setFecBaja( Date fecBaja ) {
        this.fecBaja = fecBaja;
    }
    public Date getFecBaja() {
        return this.fecBaja;
    }

    //--- DATABASE MAPPING : MOTIVO_BAJA ( VARCHAR2 ) 
    public void setMotivoBaja( String motivoBaja ) {
        this.motivoBaja = motivoBaja;
    }
    public String getMotivoBaja() {
        return this.motivoBaja;
    }
    
    //--- DATABASE MAPPING : OBJETO_CONV( VARCHAR2 ) 
    public void setObjetoConvenio( String objetoConvenio ) {
        this.objetoConvenio = objetoConvenio;
    }
    public String getObjetoConvenio() {
        return this.objetoConvenio;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setEntidades( EntidadesEntity entidades ) {
        this.entidades = entidades;
    }
    public EntidadesEntity getEntidades() {
        return this.entidades;
    }


    public Long getIdEntidades() {
		return idEntidades;
	}

	public void setIdEntidades(Long idEntidades) {
		this.idEntidades = idEntidades;
	}

	@Override
	public String toString() {
		return "ConveniosEntity [idConvenio=" + idConvenio + ", idEntidades=" + idEntidades + ", fecIniConv="
				+ fecIniConv + ", fecFirmaConv=" + fecFirmaConv + ", observaciones=" + observaciones + ", objetoConvenio=" + objetoConvenio + ", fecBaja="
				+ fecBaja + ", motivoBaja=" + motivoBaja + ", entidades=" + entidades + "]";
	} 

}
