/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "CONV_CONTACTOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CONV_CONTACTOS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ConvContactosEntity.countAll", query="SELECT COUNT(x) FROM ConvContactosEntity x" )
} )
@SequenceGenerator(name= "convContactos_id_seq_gen", sequenceName="CINETI.SEQ_CONV_CONTACTOS", allocationSize=5,initialValue=100)
public class ConvContactosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "convContactos_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_CONV_CONTACTOS", nullable=false)
    private Long idConvContactos    ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@Column(name="ID_CONVENIO")
    private Long idConvenio   ;

	@Column(name="ID_PERSONA")
    private Long idPersona   ;
    
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@ManyToOne
    @JoinColumn(name="ID_CONVENIO", referencedColumnName="ID_CONVENIO", insertable=false, updatable=false)
    private ConveniosEntity convenio ;

	@ManyToOne
    @JoinColumn(name="ID_PERSONA", referencedColumnName="ID_PERSONA", insertable=false, updatable=false)
    private PersContactoEntity persona;
   
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ConvContactosEntity() {
		super();
	}

	public Long getIdConvContactos() {
		return idConvContactos;
	}

	public ConveniosEntity getConvenio() {
		return convenio;
	}

	public void setConvenio(ConveniosEntity convenio) {
		this.convenio = convenio;
	}

	public PersContactoEntity getPersona() {
		return persona;
	}

	public void setPersona(PersContactoEntity persona) {
		this.persona = persona;
	}

	public void setIdConvContactos(Long idConvContactos) {
		this.idConvContactos = idConvContactos;
	}

	public Long getIdConvenio() {
		return idConvenio;
	}

	public void setIdConvenio(Long idConvenio) {
		this.idConvenio = idConvenio;
	}

	public Long getIdPersona() {
		return idPersona;
	}

	public void setIdPersona(Long idPersona) {
		this.idPersona = idPersona;
	}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------

	@Override
	public String toString() {
		return "ConvContactosEntity [idConvContactos=" + idConvContactos + ", idConvenio=" + idConvenio + ", idPersona="
				+ idPersona + ", convenio=" + convenio + ", persona=" + persona + "]";
	}

}
