/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "PERS_CONTACTO"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="PERS_CONTACTO", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name = "PersContactoEntity.countAll", query="SELECT COUNT(x) FROM PersContactoEntity x" ),
  @NamedQuery ( name = "findPersContactoEntityByIdEntidad", query="Select p FROM PersContactoEntity p WHERE p.idEntidad = :idEntidad ORDER BY p.nombre ASC"),
  @NamedQuery ( name = "findPersContactoEntityByIdCesion", query="Select p FROM PersContactoEntity p, CesContactosEntity cc where p.idPersona = cc.idPersona and cc.idCesiones = :idCesion"),
  @NamedQuery ( name = "findPersContactoEntityByIdConvenio", query="Select p FROM PersContactoEntity p, ConvContactosEntity cc where p.idPersona = cc.idPersona and cc.idConvenio = :idConvenio")
} )
@SequenceGenerator(name= "persContacto_id_seq_gen", sequenceName="CINETI.SEQ_PERS_CONTACTO", allocationSize=5,initialValue=100)
public class PersContactoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "persContacto_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_PERSONA", nullable=false)
    private Long idPersona    ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOMBRE", length=100)
    private String nombre;

    @Column(name="CARGO", length=100)
    private String cargo;

    @Column(name="TELEFONOS", length=100)
    private String telefonos;

    @Column(name="EMAIL", length=256)
    private String email;

    @Column(name="FAX", length=100)
    private String fax;

    @Column(name="DIRECCION", length=300)
    private String direccion;

    @Column(name="OBSERVACIONES", length=300)
    private String observaciones;
    
    @Column(name="ID_ENTIDAD", nullable=false)
    private Long idEntidad;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_ACTUALIZACION")
    private Date fecActualizacion;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PersContactoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPersona( Long idPersona ) {
        this.idPersona = idPersona ;
    }
    public Long getIdPersona() {
        return this.idPersona;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setCargo( String cargo ) {
        this.cargo = cargo;
    }
    
    public String getCargo() {
        return this.cargo;
    }

    public void setTelefonos( String telefonos ) {
        this.telefonos = telefonos;
    }
    
    public String getTelefonos() {
        return this.telefonos;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    
    public String getEmail() {
        return this.email;
    }

    public void setFax( String fax ) {
        this.fax = fax;
    }
    
    public String getFax() {
        return this.fax;
    }

    public void setDireccion( String direccion ) {
        this.direccion = direccion;
    }
    
    public String getDireccion() {
        return this.direccion;
    }

    public void setObservaciones( String observaciones ) {
        this.observaciones = observaciones;
    }
    
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setFecActualizacion( Date fecActualizacion ) {
        this.fecActualizacion = fecActualizacion;
    }
    public Date getFecActualizacion() {
        return this.fecActualizacion;
    }

    public Long getIdEntidad() {
		return idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Override
	public String toString() {
		return "PersContactoEntity [idPersona=" + idPersona + ", nombre=" + nombre + ", cargo=" + cargo + ", telefonos="
				+ telefonos + ", email=" + email + ", fax=" + fax + ", direccion=" + direccion + ", observaciones="
				+ observaciones + ", idEntidad=" + idEntidad + ", fecActualizacion=" + fecActualizacion + "]";
	} 

}
