/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "PROVINCIAS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="PROVINCIAS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name = "ProvinciasEntity.countAll", query="SELECT COUNT(x) FROM ProvinciasEntity x" ),
  @NamedQuery ( name = "findProvinciasEntityByIdUsuario", query="SELECT p FROM ProvinciasEntity p, UsuariosProvinciasEntity up WHERE p.idProvincia = up.idProvincia AND up.idUsuario = :idUsuario ORDER BY p.descProvincia ASC")
} )
@SequenceGenerator(name= "provincias_id_seq_gen", sequenceName="CINETI.SEQ_PROVINCIAS", allocationSize=5,initialValue=100)
public class ProvinciasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "provincias_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_PROVINCIA", nullable=false)
    private Long idProvincia;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="DESC_PROVINCIA", length=100)
    private String descProvincia;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    /*@OneToMany(mappedBy="provincias", targetEntity=LocalidadesEntity.class)
    private List<LocalidadesEntity> listOfLocalidades;
	*/
    /*@OneToMany( mappedBy="provincias", targetEntity=EquipamientoEntity.class)
    private List<EquipamientoEntity> listOfEquipamiento;

    @OneToMany(mappedBy="provincias", targetEntity=UsuariosProvinciasEntity.class)
    private List<UsuariosProvinciasEntity> listOfUsuariosProvincias;

    @OneToMany( mappedBy="provincias", targetEntity=UsuariosEntity.class)
    private List<UsuariosEntity> listOfUsuarios;
	*/
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ProvinciasEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdProvincia( Long idProvincia ) {
        this.idProvincia = idProvincia ;
    }
    public Long getIdProvincia() {
        return this.idProvincia;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DESC_PROVINCIA ( VARCHAR2 ) 
    public void setDescProvincia( String descProvincia ) {
        this.descProvincia = descProvincia;
    }
    public String getDescProvincia() {
        return this.descProvincia;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
   

//    public void setListOfEtiEvidencial( List<EtiEvidencialEntity> listOfEtiEvidencial ) {
//        this.listOfEtiEvidencial = listOfEtiEvidencial;
//    }
//    public List<EtiEvidencialEntity> getListOfEtiEvidencial() {
//        return this.listOfEtiEvidencial;
//    }

   /* public void setListOfEtiDigital( List<EtiDigitalEntity> listOfEtiDigital ) {
        this.listOfEtiDigital = listOfEtiDigital;
    }
    public List<EtiDigitalEntity> getListOfEtiDigital() {
        return this.listOfEtiDigital;
    }

    public void setListOfAnlDrogas( List<AnlDrogasEntity> listOfAnlDrogas ) {
        this.listOfAnlDrogas = listOfAnlDrogas;
    }
    public List<AnlDrogasEntity> getListOfAnlDrogas() {
        return this.listOfAnlDrogas;
    }*/

//    public void setListOfCinemometro( List<CinemometroEntity> listOfCinemometro ) {
//        this.listOfCinemometro = listOfCinemometro;
//    }
//    public List<CinemometroEntity> getListOfCinemometro() {
//        return this.listOfCinemometro;
//    }

//    public void setListOfEquipamiento( List<EquipamientoEntity> listOfEquipamiento ) {
//        this.listOfEquipamiento = listOfEquipamiento;
//    }
//    public List<EquipamientoEntity> getListOfEquipamiento() {
//        return this.listOfEquipamiento;
//    }
//    
//    public void setListOfUsuariosProvincias( List<UsuariosProvinciasEntity> listOfUsuariosProvincias ) {
//        this.listOfUsuariosProvincias = listOfUsuariosProvincias;
//    }
//    public List<UsuariosProvinciasEntity> getListOfUsuariosProvincias() {
//        return this.listOfUsuariosProvincias;
//    }
//
////    public void setListOfVehiculo( List<VehiculoEntity> listOfVehiculo ) {
////        this.listOfVehiculo = listOfVehiculo;
////    }
////    public List<VehiculoEntity> getListOfVehiculo() {
////        return this.listOfVehiculo;
////    }
//
//    public void setListOfUsuarios( List<UsuariosEntity> listOfUsuarios ) {
//        this.listOfUsuarios = listOfUsuarios;
//    }
//    public List<UsuariosEntity> getListOfUsuarios() {
//        return this.listOfUsuarios;
//    }


    @Override
	public String toString() {
		return "ProvinciasEntity [idProvincia=" + idProvincia + ", descProvincia=" + descProvincia + "]";
	} 

}
