/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "RES_ANL_DROGAS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="RES_ANL_DROGAS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ResAnlDrogasEntity.countAll", query="SELECT COUNT(x) FROM ResAnlDrogasEntity x" )
} )
@SequenceGenerator(name= "resAnlDrogas_id_seq_gen", sequenceName="CINETI.SEQ_RES_ANL_DROGAS", allocationSize=5,initialValue=100)
public class ResAnlDrogasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "resAnlDrogas_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_RES_ANL_DROGAS", nullable=false)
    private Long idResAnlDrogas    ;

    

	//----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

	@Column(name="ANO")
    private Long ano       ;


	@Column(name="MES")
    private Long mes       ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="RES_NEG")
    private Long resNeg       ;

    @Column(name="RES_POS")
    private Long resPos       ;

    @Column(name="ID_CESION")
    private Long idCesiones;
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_CESION", referencedColumnName="ID_CESION", insertable=false, updatable=false)
    private CesionesEntity cesiones    ;
	
  
	//----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ResAnlDrogasEntity() {
		super();
		}
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    public Long getIdResAnlDrogas() {
		return idResAnlDrogas;
	}

	public void setIdResAnlDrogas(Long idResAnlDrogas) {
		this.idResAnlDrogas = idResAnlDrogas;
	}

	public Long getAno() {
		return ano;
	}

	public void setAno(Long ano) {
		this.ano = ano;
	}

	public Long getMes() {
		return mes;
	}

	public void setMes(Long mes) {
		this.mes = mes;
	}


    public Long getIdCesiones() {
		return idCesiones;
	}

	public void setIdCesiones(Long idCesiones) {
		this.idCesiones = idCesiones;
	}

	public CesionesEntity getCesiones() {
		return cesiones;
	}

	public void setCesiones(CesionesEntity cesiones) {
		this.cesiones = cesiones;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : RES_NEG ( NUMBER ) 
    public void setResNeg( Long resNeg ) {
        this.resNeg = resNeg;
    }
    public Long getResNeg() {
        return this.resNeg;
    }

    //--- DATABASE MAPPING : RES_POS ( NUMBER ) 
    public void setResPos( Long resPos ) {
        this.resPos = resPos;
    }
    public Long getResPos() {
        return this.resPos;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
  


	@Override
	public String toString() {
		return "ResAnlDrogasEntity [idResAnlDrogas=" + idResAnlDrogas + ", ano=" + ano + ", mes=" + mes + ", resNeg="
				+ resNeg + ", resPos=" + resPos + ", idCesiones=" + idCesiones + ", cesiones=" + cesiones + "]";
	}


    
}
