/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "RES_CINEMOMETRO"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="RES_CINEMOMETRO", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ResCinemometroEntity.countAll", query="SELECT COUNT(x) FROM ResCinemometroEntity x" )
} )
@SequenceGenerator(name= "resCinemometro_id_seq_gen", sequenceName="CINETI.SEQ_RES_CINEMOMETRO", allocationSize=5,initialValue=100)
public class ResCinemometroEntity implements Serializable {

    private static final long serialVersionUID = 1L;

  //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "resCinemometro_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_RES_CINEMOMETRO", nullable=false)
    private Long idResCinemometro    ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

	@Column(name="ANO")
    private Long ano       ;

	@Column(name="MES")
    private Long mes       ;
    
    @Column(name="NUM_VEH_CONT")
    private Long numVehCont   ;

    @Column(name="NUM_VEH_DEN")
    private Long numVehDen    ;

    @Column(name="NUM_VEH_NOT")
    private Long numVehNot    ;

    @Column(name="NUM_VEH_COD_PENAL")
    private Long numVehCodPenal ;

    @Column(name="ID_CESION")
    private Long idCesiones;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_CESION", insertable=false, updatable=false)
    private CesionesEntity cesiones    ;
	

	//----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ResCinemometroEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
   
	public Long getIdResCinemometro() {
		return idResCinemometro;
	}

	public void setIdResCinemometro(Long idResCinemometro) {
		this.idResCinemometro = idResCinemometro;
	}



    public Long getIdCesiones() {
		return idCesiones;
	}

	public void setIdCesiones(Long idCesiones) {
		this.idCesiones = idCesiones;
	}

	public CesionesEntity getCesiones() {
		return cesiones;
	}

	public void setCesiones(CesionesEntity cesiones) {
		this.cesiones = cesiones;
	}
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NUM_VEH_CONT ( NUMBER ) 
   
	public Long getAno() {
		return ano;
	}

	public void setAno(Long ano) {
		this.ano = ano;
	}

	public Long getMes() {
		return mes;
	}

	public void setMes(Long mes) {
		this.mes = mes;
	}

	public void setNumVehCont( Long numVehCont ) {
        this.numVehCont = numVehCont;
    }
    public Long getNumVehCont() {
        return this.numVehCont;
    }

    //--- DATABASE MAPPING : NUM_VEH_DEN ( NUMBER ) 
    public void setNumVehDen( Long numVehDen ) {
        this.numVehDen = numVehDen;
    }
    public Long getNumVehDen() {
        return this.numVehDen;
    }

    //--- DATABASE MAPPING : NUM_VEH_NOT ( NUMBER ) 
    public void setNumVehNot( Long numVehNot ) {
        this.numVehNot = numVehNot;
    }
    public Long getNumVehNot() {
        return this.numVehNot;
    }

    //--- DATABASE MAPPING : NUM_VEH_COD_PENAL ( NUMBER ) 
    public void setNumVehCodPenal( Long numVehCodPenal ) {
        this.numVehCodPenal = numVehCodPenal;
    }
    public Long getNumVehCodPenal() {
        return this.numVehCodPenal;
    }

	@Override
	public String toString() {
		return "ResCinemometroEntity [idResCinemometro=" + idResCinemometro + ", ano=" + ano + ", mes=" + mes
				+ ", numVehCont=" + numVehCont + ", numVehDen=" + numVehDen + ", numVehNot=" + numVehNot
				+ ", numVehCodPenal=" + numVehCodPenal + ", idCesiones=" + idCesiones + ", cesiones=" + cesiones + "]";
	}



}
