/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "RES_ETI_EVIDENCIAL"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="RES_ETI_EVIDENCIAL", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ResEtiEvidencialEntity.countAll", query="SELECT COUNT(x) FROM ResEtiEvidencialEntity x" )
} )
@SequenceGenerator(name= "resEtiEvidencial_id_seq_gen", sequenceName="CINETI.SEQ_RES_ETI_EVIDENCIAL", allocationSize=5,initialValue=100)
public class ResEtiEvidencialEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "resEtiEvidencial_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_RES_ETI_EVIDENCIAL", nullable=false)
    private Long idResEtiEvidencial    ;

    

	//----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

	@Column(name="ID_CESION")
    private Long idCesiones   ;
	
	@Column(name="ANO")
    private Long ano       ;


	@Column(name="MES")
    private Long mes       ;  
    @Column(name="RES_NEG_ACC")
    private Long resNegAcc    ;

    @Column(name="RES_NEG_INF")
    private Long resNegInf    ;

    @Column(name="RES_NEG_PRE")
    private Long resNegPre    ;

    @Column(name="RES_POS_COD_PENAL")
    private Long resPosCodPenal ;

    @Column(name="RES_POS_ACC")
    private Long resPosAcc    ;

    @Column(name="RES_POS_INF")
    private Long resPosInf    ;

    @Column(name="RES_POS_PRE")
    private Long resPosPre    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_CESION", referencedColumnName="ID_CESION", insertable=false, updatable=false)
    private CesionesEntity cesiones    ;
	

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ResEtiEvidencialEntity() {
		super();
	}
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    


    public Long getIdResEtiEvidencial() {
		return idResEtiEvidencial;
	}

	public void setIdResEtiEvidencial(Long idResEtiEvidencial) {
		this.idResEtiEvidencial = idResEtiEvidencial;
	}

	public Long getAno() {
		return ano;
	}

	public void setAno(Long ano) {
		this.ano = ano;
	}

	public Long getMes() {
		return mes;
	}

	public Long getIdCesiones() {
		return idCesiones;
	}

	public void setIdCesiones(Long idCesiones) {
		this.idCesiones = idCesiones;
	}

	public CesionesEntity getCesiones() {
		return cesiones;
	}

	public void setCesiones(CesionesEntity cesiones) {
		this.cesiones = cesiones;
	}

	public void setMes(Long mes) {
		this.mes = mes;
	}

	//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : RES_NEG_ACC ( NUMBER ) 
    public void setResNegAcc( Long resNegAcc ) {
        this.resNegAcc = resNegAcc;
    }
    public Long getResNegAcc() {
        return this.resNegAcc;
    }

    //--- DATABASE MAPPING : RES_NEG_INF ( NUMBER ) 
    public void setResNegInf( Long resNegInf ) {
        this.resNegInf = resNegInf;
    }
    public Long getResNegInf() {
        return this.resNegInf;
    }

    //--- DATABASE MAPPING : RES_NEG_PRE ( NUMBER ) 
    public void setResNegPre( Long resNegPre ) {
        this.resNegPre = resNegPre;
    }
    public Long getResNegPre() {
        return this.resNegPre;
    }

    //--- DATABASE MAPPING : RES_POS_COD_PENAL ( NUMBER ) 
    public void setResPosCodPenal( Long resPosCodPenal ) {
        this.resPosCodPenal = resPosCodPenal;
    }
    public Long getResPosCodPenal() {
        return this.resPosCodPenal;
    }

    //--- DATABASE MAPPING : RES_POS_ACC ( NUMBER ) 
    public void setResPosAcc( Long resPosAcc ) {
        this.resPosAcc = resPosAcc;
    }
    public Long getResPosAcc() {
        return this.resPosAcc;
    }

    //--- DATABASE MAPPING : RES_POS_INF ( NUMBER ) 
    public void setResPosInf( Long resPosInf ) {
        this.resPosInf = resPosInf;
    }
    public Long getResPosInf() {
        return this.resPosInf;
    }

    //--- DATABASE MAPPING : RES_POS_PRE ( NUMBER ) 
    public void setResPosPre( Long resPosPre ) {
        this.resPosPre = resPosPre;
    }
    public Long getResPosPre() {
        return this.resPosPre;
    }



    @Override
	public String toString() {
		return "ResEtiEvidencialEntity [idResEtiEvidencial=" + idResEtiEvidencial + ", idCesiones=" + idCesiones
				+ ", ano=" + ano + ", mes=" + mes + ", resNegAcc=" + resNegAcc + ", resNegInf=" + resNegInf
				+ ", resNegPre=" + resNegPre + ", resPosCodPenal=" + resPosCodPenal + ", resPosAcc=" + resPosAcc
				+ ", resPosInf=" + resPosInf + ", resPosPre=" + resPosPre + ", cesiones=" + cesiones + "]";
	}

}
