/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "TIPO_VERIFICACION"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="TIPO_VERIFICACION", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TipoVerificacionEntity.countAll", query="SELECT COUNT(x) FROM TipoVerificacionEntity x" )
} )
@SequenceGenerator(name= "tipoVerificacion_id_seq_gen", sequenceName="CINETI.SEQ_TIPO_VERIFICACION", allocationSize=5,initialValue=100)
public class TipoVerificacionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "tipoVerificacion_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_TIPO_VERIFICACION", nullable=false)
    private Long idTipoVerificacion ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="DESC_TIPO_VERIFICACION", length=100)
    private String     descTipoVerificacion ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    /*@OneToMany(mappedBy="tipoVerificacion", targetEntity=VerificacionesEntity.class)
    private List<VerificacionesEntity> listOfVerificaciones;
	*/

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TipoVerificacionEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTipoVerificacion( Long idTipoVerificacion ) {
        this.idTipoVerificacion = idTipoVerificacion ;
    }
    public Long getIdTipoVerificacion() {
        return this.idTipoVerificacion;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DESC_TIPO_VERIFICACION ( VARCHAR2 ) 
    public void setDescTipoVerificacion( String descTipoVerificacion ) {
        this.descTipoVerificacion = descTipoVerificacion;
    }
    public String getDescTipoVerificacion() {
        return this.descTipoVerificacion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    /*public void setListOfVerificaciones( List<VerificacionesEntity> listOfVerificaciones ) {
        this.listOfVerificaciones = listOfVerificaciones;
    }
    public List<VerificacionesEntity> getListOfVerificaciones() {
        return this.listOfVerificaciones;
    }*/


    @Override
	public String toString() {
		return "TipoVerificacionEntity [idTipoVerificacion=" + idTipoVerificacion + ", descTipoVerificacion="
				+ descTipoVerificacion + "]";
	} 

}
