/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "TIPO_PERFILES"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="TIPO_PERFILES", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TipoPerfilesEntity.countAll", query="SELECT COUNT(x) FROM TipoPerfilesEntity x" )
} )
@SequenceGenerator(name= "tipoPerfiles_id_seq_gen", sequenceName="CINETI.SEQ_TIPO_PERFILES", allocationSize=5,initialValue=100)
public class TipoPerfilesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "tipoPerfiles_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_PERFIL", nullable=false)
    private Long     idPerfil     ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="CODIGO_PERFIL", length=50)
    private String     codigoPerfil   ;

    @Column(name="DESC_PERFIL", length=200)
    private String     descPerfil   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    /*@OneToMany(mappedBy="tipoPerfiles", targetEntity=UsuariosPerfilesEntity.class)
    private List<UsuariosPerfilesEntity> listOfUsuariosPerfiles;
	*/

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TipoPerfilesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPerfil( Long idPerfil ) {
        this.idPerfil = idPerfil ;
    }
    public Long getIdPerfil() {
        return this.idPerfil;
    }

  

	public String getCodigoPerfil() {
		return codigoPerfil;
	}

	public void setCodigoPerfil(String codigoPerfil) {
		this.codigoPerfil = codigoPerfil;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DESC_PERFIL ( VARCHAR2 ) 
    public void setDescPerfil( String descPerfil ) {
        this.descPerfil = descPerfil;
    }
    public String getDescPerfil() {
        return this.descPerfil;
    }

	@Override
	public String toString() {
		return "TipoPerfilesEntity [idPerfil=" + idPerfil + ", codigoPerfil=" + codigoPerfil + ", descPerfil="
				+ descPerfil + "]";
	}


    
  	
  	


}
