/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "TIPO_PRIVILEGIOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="TIPO_PRIVILEGIOS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TipoPrivilegiosEntity.countAll", query="SELECT COUNT(x) FROM TipoPrivilegiosEntity x" )
} )
@SequenceGenerator(name= "tipoPrivilegios_id_seq_gen", sequenceName="CINETI.SEQ_TIPO_PRIVILEGIOS", allocationSize=5,initialValue=100)
public class TipoPrivilegiosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "tipoPrivilegios_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_PRIVILEGIO", nullable=false)
    private Long     idPrivilegio ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="CODIGO_PRIVIL", length=50)
    private String     codigoPrivilegio ;
   
    @Column(name="DESC_PRIVILEGIO", length=50)
    private String     descPrivilegio ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    /*@OneToMany(mappedBy="tipoPrivilegios", targetEntity=UsuariosPerfilesEntity.class)
    private List<UsuariosPerfilesEntity> listOfUsuariosPerfiles;
	*/

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TipoPrivilegiosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPrivilegio( Long idPrivilegio ) {
        this.idPrivilegio = idPrivilegio ;
    }
    public Long getIdPrivilegio() {
        return this.idPrivilegio;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DESC_PRIVILEGIO ( VARCHAR2 ) 
    public void setDescPrivilegio( String descPrivilegio ) {
        this.descPrivilegio = descPrivilegio;
    }
    public String getDescPrivilegio() {
        return this.descPrivilegio;
    }

	public String getCodigoPrivilegio() {
		return codigoPrivilegio;
	}

	public void setCodigoPrivilegio(String codigoPrivilegio) {
		this.codigoPrivilegio = codigoPrivilegio;
	}


	@Override
	public String toString() {
		return "TipoPrivilegiosEntity [idPrivilegio=" + idPrivilegio + ", codigoPrivilegio=" + codigoPrivilegio
				+ ", descPrivilegio=" + descPrivilegio + "]";
	}


}
