/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "TIPO_CAMPANA"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="TIPO_CAMPANA", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TipoCampanaEntity.countAll", query="SELECT COUNT(x) FROM TipoCampanaEntity x" )
} )
@SequenceGenerator(name= "tipoCampana_id_seq_gen", sequenceName="CINETI.SEQ_TIPO_CAMPANA", allocationSize=5,initialValue=100)
public class TipoCampanaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "tipoCampana_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_TIPO", nullable=false)
    private Long idTipo       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="DESC_TIPO", length=100)
    private String     descTipo     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
//    @OneToMany(mappedBy="tipoCampana", targetEntity=CampanaEntity.class)
//    private List<CampanaEntity> listOfCampana;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TipoCampanaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTipo( Long idTipo ) {
        this.idTipo = idTipo ;
    }
    public Long getIdTipo() {
        return this.idTipo;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DESC_TIPO ( VARCHAR2 ) 
    public void setDescTipo( String descTipo ) {
        this.descTipo = descTipo;
    }
    public String getDescTipo() {
        return this.descTipo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
//    public void setListOfCampana( List<CampanaEntity> listOfCampana ) {
//        this.listOfCampana = listOfCampana;
//    }
//    public List<CampanaEntity> getListOfCampana() {
//        return this.listOfCampana;
//    }


    @Override
	public String toString() {
		return "TipoCampanaEntity [idTipo=" + idTipo + ", descTipo=" + descTipo + "]";
	} 

}
