/*
 * Created on 6 abr 2016 ( Time 20:03:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "USUARIOS_PROVINCIAS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="USUARIOS_PROVINCIAS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UsuariosProvinciasEntity.countAll", query="SELECT COUNT(x) FROM UsuariosProvinciasEntity x" )
} )
@SequenceGenerator(name= "usuariosProvincias_id_seq_gen", sequenceName="CINETI.SEQ_USUARIOS_PROVINCIAS", allocationSize=5,initialValue=100)
public class UsuariosProvinciasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "usuariosProvincias_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_USUARIOS_PROVINCIAS", nullable=false)
    private Long idUsuariosProvincias    ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@Column(name="ID_USUARIO")
    private Long idUsuario;
	
	@Column(name="ID_PROVINCIA")
    private Long idProvincia   ;
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@ManyToOne
    @JoinColumn(name="ID_USUARIO", referencedColumnName="ID_USUARIO", insertable=false, updatable=false)
    private UsuariosEntity usuarios  ;


	@ManyToOne
    @JoinColumn(name="ID_PROVINCIA", referencedColumnName="ID_PROVINCIA", insertable=false, updatable=false)
    private ProvinciasEntity provincias  ;
	 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UsuariosProvinciasEntity() {
		super(); 
    }
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------


	public Long getIdUsuariosProvincias() {
		return idUsuariosProvincias;
	}

	public void setIdUsuariosProvincias(Long idUsuariosProvincias) {
		this.idUsuariosProvincias = idUsuariosProvincias;
	}

	public Long getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Long getIdProvincia() {
		return idProvincia;
	}

	public void setIdProvincia(Long idProvincia) {
		this.idProvincia = idProvincia;
	}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------

	@Override
	public String toString() {
		return "UsuariosProvinciasEntity [idUsuariosProvincias=" + idUsuariosProvincias + ", idUsuario=" + idUsuario
				+ ", idProvincia=" + idProvincia + ", usuarios=" + usuarios + ", provincias=" + provincias + "]";
	}

}
