/*
 * Created on 6 abr 2016 ( Time 20:03:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "ENTIDADES"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="USUARIOS_PARAMETROS", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UsuariosParametrosEntity.countAll", query="SELECT COUNT(x) FROM UsuariosParametrosEntity x" )
} )
@SequenceGenerator(name= "usuar_param_id_seq_gen", sequenceName="CINETI.SEQ_USUARIOS_PARAM", allocationSize=5,initialValue=100)
public class UsuariosParametrosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "usuar_param_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID", nullable=false)
    private Long id   ;


	//----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ID_USUARIO")
    private Long idUsuario   ;
    
    @Column(name="ID_PARAM")
    private Long  idParam       ;

    @Column(name="VALUE_PARAM", length=100)
    private String     valueParam    ;
	
    @ManyToOne
    @JoinColumn(name="ID_PARAM", referencedColumnName="ID", insertable=false, updatable=false)
    private ParametrosEntity parametros ;
	
    @ManyToOne
    @JoinColumn(name="ID_USUARIO", referencedColumnName="ID_USUARIO", insertable=false, updatable=false)
    private UsuariosEntity usuario ;
	

	//----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UsuariosParametrosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOMBRE ( VARCHAR2 ) 

    public Long getIdParam() {
		return idParam;
	}

	public void setIdTipoEntidad(Long idParam) {
		this.idParam = idParam;
	}
	
    public void setValueParam( String valueParam ) {
        this.valueParam = valueParam;
    }
    public String getValueParam() {
        return this.valueParam;
    }

	public Long getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public void setIdParam(Long idParam) {
		this.idParam = idParam;
	}

	@Override
	public String toString() {
		return "UsuariosParametrosEntity [id=" + id + ", idUsuario=" + idUsuario + ", idParam=" + idParam
				+ ", valueParam=" + valueParam + ", parametros=" + parametros + ", usuario=" + usuario + "]";
	}


   

}
