/*
 * Created on 6 abr 2016 ( Time 20:03:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cgt.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "VERIFICACIONES"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="VERIFICACIONES", schema="CINETI" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="VerificacionesEntity.countAll", query="SELECT COUNT(x) FROM VerificacionesEntity x" )
} )
@SequenceGenerator(name= "verificaciones_id_seq_gen", sequenceName="CINETI.SEQ_VERIFICACIONES", allocationSize=5,initialValue=100)
public class VerificacionesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(generator = "verificaciones_id_seq_gen", strategy = GenerationType.SEQUENCE)
    @Column(name="ID_VERIFICACION", nullable=false)
    private Long idVerificacion ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ID_EQUIPAMIENTO")
    private Long idEquipamiento   ;
	

	@Column(name="ID_TIPO_VERIFICACION")
    private Long idTipoVerificacion   ;
	
    @Column(name="ID_CESION")
    private Long idCesiones     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_LLEGADA_ENT")
    private Date       fecLlegadaEnt ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_ENVIO_VERIF")
    private Date       fecEnvioVerif ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_VERIF")
    private Date       fecVerif     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_LLEGADA_VERIF")
    private Date       fecLlegadaVerif ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_ENTREGA_ENT")
    private Date       fecEntregaEnt ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_PET_A_ENT")
    private Date fecPetAEnt;
    
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_DEV_A_ENT")
    private Date fecDevEntidad;


	@Column(name="VERIFICACION_CERRADA", length=1)
    private String     verificacionCerrada ;
    
    @Column(name="MOTIVO_VERIFICACION")
    private String motivoVerificacion;

	// "idTipoEquipamiento" (column "ID_TIPO_EQUIPAMIENTO") is not defined by itself because used as FK in a link 
	// "idTipoVerificacion" (column "ID_TIPO_VERIFICACION") is not defined by itself because used as FK in a link 



	//----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_TIPO_VERIFICACION", referencedColumnName="ID_TIPO_VERIFICACION", insertable=false, updatable=false)
    private TipoVerificacionEntity tipoVerificacion;

    
	@ManyToOne
    @JoinColumn(name="ID_EQUIPAMIENTO", referencedColumnName="ID", insertable=false, updatable=false)
    private EquipamientoEntity equipamiento;

    @ManyToOne
    @JoinColumn(name="ID_CESION", referencedColumnName="ID_CESION", insertable=false, updatable=false)
    private CesionesEntity cesiones;
	
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public VerificacionesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdVerificacion( Long idVerificacion ) {
        this.idVerificacion = idVerificacion ;
    }
    public Long getIdVerificacion() {
        return this.idVerificacion;
    }
	public Long getIdEquipamiento() {
		return idEquipamiento;
	}

	public void setIdEquipamiento(Long idEquipamiento) {
		this.idEquipamiento = idEquipamiento;
	}

	public Long getIdTipoVerificacion() {
		return idTipoVerificacion;
	}

	public void setIdTipoVerificacion(Long idTipoVerificacion) {
		this.idTipoVerificacion = idTipoVerificacion;
	}

	public TipoVerificacionEntity getTipoVerificacion() {
		return tipoVerificacion;
	}

	public void setTipoVerificacion(TipoVerificacionEntity tipoVerificacion) {
		this.tipoVerificacion = tipoVerificacion;
	}

	public EquipamientoEntity getEquipamiento() {
		return equipamiento;
	}

	public void setEquipamiento(EquipamientoEntity equipamiento) {
		this.equipamiento = equipamiento;
	}

	public CesionesEntity getCesiones() {
		return cesiones;
	}

	public void setCesiones(CesionesEntity cesiones) {
		this.cesiones = cesiones;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NUM_SERIE ( VARCHAR2 ) 
  
    //--- DATABASE MAPPING : ID_CESION ( NUMBER ) 
    public void setIdCesiones( Long idCesion ) {
        this.idCesiones = idCesion;
    }
    public Long getIdCesiones() {
        return this.idCesiones;
    }

    //--- DATABASE MAPPING : FEC_LLEGADA_ENT ( DATE ) 
    public void setFecLlegadaEnt( Date fecLlegadaEnt ) {
        this.fecLlegadaEnt = fecLlegadaEnt;
    }
    public Date getFecLlegadaEnt() {
        return this.fecLlegadaEnt;
    }

    //--- DATABASE MAPPING : FEC_ENVIO_VERIF ( DATE ) 
    public void setFecEnvioVerif( Date fecEnvioVerif ) {
        this.fecEnvioVerif = fecEnvioVerif;
    }
    public Date getFecEnvioVerif() {
        return this.fecEnvioVerif;
    }

    //--- DATABASE MAPPING : FEC_VERIF ( DATE ) 
    public void setFecVerif( Date fecVerif ) {
        this.fecVerif = fecVerif;
    }
    public Date getFecVerif() {
        return this.fecVerif;
    }

    //--- DATABASE MAPPING : FEC_LLEGADA_VERIF ( DATE ) 
    public void setFecLlegadaVerif( Date fecLlegadaVerif ) {
        this.fecLlegadaVerif = fecLlegadaVerif;
    }
    public Date getFecLlegadaVerif() {
        return this.fecLlegadaVerif;
    }

    //--- DATABASE MAPPING : FEC_ENTREGA_ENT ( DATE ) 
    public void setFecEntregaEnt( Date fecEntregaEnt ) {
        this.fecEntregaEnt = fecEntregaEnt;
    }
    public Date getFecEntregaEnt() {
        return this.fecEntregaEnt;
    }

    //--- DATABASE MAPPING : VERIFICACION_CERRADA ( VARCHAR2 ) 
    public void setVerificacionCerrada( String verificacionCerrada ) {
        this.verificacionCerrada = verificacionCerrada;
    }
    public String getVerificacionCerrada() {
        return this.verificacionCerrada;
    }

	public Date getFecPetAEnt() {
		return fecPetAEnt;
	}

	public void setFecPetAEnt(Date fecPetAEnt) {
		this.fecPetAEnt = fecPetAEnt;
	}


    public String getMotivoVerificacion() {
		return motivoVerificacion;
	}

	public void setMotivoVerificacion(String motivoVerificacion) {
		this.motivoVerificacion = motivoVerificacion;
	}
	
    public Date getFecDevEntidad() {
    	return fecDevEntidad;
	}
	
	public void setFecDevEntidad(Date fecDevEntidad) {
		this.fecDevEntidad = fecDevEntidad;
	}
	
	@Override
	public String toString() {
		return "VerificacionesEntity [idVerificacion=" + idVerificacion + ", idEquipamiento=" + idEquipamiento
				+ ", idTipoVerificacion=" + idTipoVerificacion + ", idCesiones=" + idCesiones + ", fecLlegadaEnt="
				+ fecLlegadaEnt + ", fecEnvioVerif=" + fecEnvioVerif + ", fecVerif=" + fecVerif + ", fecLlegadaVerif="
				+ fecLlegadaVerif + ", fecEntregaEnt=" + fecEntregaEnt + ", fecPetAEnt=" + fecPetAEnt
				+ ", verificacionCerrada=" + verificacionCerrada +", motivoVerificacion=" + motivoVerificacion +", fecDevEntidad=" + fecDevEntidad +"]";
	}




}
